### ISSUE TITLE
Dynamically adding Children/Nodes Do not Update Tree.

### ISSUE THREAD

**Issue by pranavghate30** [debabratapatra/ngtreegrid#2]
Hi Deb. 

I tried to have a api call on expand event and then tried to add response to the tree dataSource. 

The dataSource shows changes but DOM do not update. 

DOM only updates when I reload it using *ngIf.

Thank you for wonderful plugin and Helping us out in a very very short time, for the issue

**Comment by debabratapatra** [comment]
Do you use ngtreegrid or [angular-tree-grid](https://github.com/debabratapatra/angular-tree-grid)?

**Comment by pranavghate30** [comment]
no by mistake i did it...

**Comment by debabratapatra** [comment]
No problem. Closing it.
