### ISSUE TITLE
Build error due to typo in the imports of tree-head.component.ts

### ISSUE THREAD

**Issue by cfroment** [debabratapatra/ngtreegrid#3]
**Describe the bug**
When performing a npm build of the project using the library, a TS2307 error occurs due to a typo (case sensitivity) in the imports of the tree-head.component.ts file.

`import { Store } from '../../../../Store/Store';` should be `import { Store } from '../../../../store/Store';` as the directory is named store (mind the lowercase).

**To Reproduce**
1. Perform a npm build --configuration=production --aot

**Expected behavior**
Build is successful and does not throw a TS2307 error.

**Screenshots**
![image](https://user-images.githubusercontent.com/12730480/61053595-203e2b80-a3ee-11e9-9535-6f8641557e7a.png)

**Additional context**
The error happens systematically when running the build using Gitlab CI; no errors during the same build using a local Windows 10 workstation.

**Comment by debabratapatra** [comment]
@cfroment thanks for describing the bug. I think I fixed this bug. Please use the latest build(3.3.2). Please let me know if this fixes this issue.
