### ISSUE TITLE
Unable to groupby based on 2 columns

### ISSUE THREAD

**Issue by minijh** [debabratapatra/ngtreegrid#6]
Thanks for this easy to integrate library. I am stuck with an issue and needed your insight. @debabratapatra 

I want to create a multi-level grid based on the below data. The challenge I am facing is how to display sum of cost field based on month. For eg, the view should look like this -

**AccountName   ShortName     Comp    Sum-of-Jan 2022   Sum-of-Feb 2022   Sum-of-Mar 2022**

where sum is the sum of cost key in json data.

sample json - 
[{
        "accountName": "account 1,
        "shortName": "short1",
        "comp": "abc",
        "cost": 0.0,
        "month": "Jan 2022"
    },
{
        "accountName": "account 1,
        "shortName": "short2",
        "comp": "abc",
        "cost": 5.0,
        "month": "Feb 2022"
    },
{
        "accountName": "account 1,
        "shortName": "short1",
        "comp": "def",
        "cost": 0.0,
        "month": "Jan 2022"
    },
{
        "accountName": "account 2,
        "shortName": "short1",
        "comp": "abc",
        "cost": 0.0,
        "month": "Mar 2022"
    }]

**Comment by debabratapatra** [comment]
Sorry, Can you please explain more? Maybe send a screenshot of what you want to achieve?

**Comment by minijh** [comment]
Thanks for your reply. Here is the screenshot of what I want to achieve.
Any help would be appreciated.

**Comment by debabratapatra** [comment]
There is no screenshot :)

**Comment by minijh** [comment]
Attaching again. 
![Uploading C215F47B-D5B6-453A-86DD-63FDA7A49401.jpeg…]()

**Comment by debabratapatra** [comment]
Not enough information to reproduce. Closing.
